---
branches:
  -
    name: master
    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        dismissal_restrictions:
          teams:
            - sloans
          users: []
        require_code_owner_reviews: false
      required_status_checks:
        contexts: []
        strict: true
      restrictions: "null"
repository:
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_squash_merge: true
  default_branch: master
  has_issues: true
  has_wiki: true
  private: false
teams:
  -
    name: sloans
    permission: admin
  -
    name: others
    permission: admin
