branches:
  -
    name: master
    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        dismissal_restrictions:
          teams:
            - sloans
          users:
            - jwsloan
        require_code_owner_reviews: true
      required_status_checks:
        contexts: []
        strict: true
      restrictions:
        users:
          - jwsloan
        teams:
          - sloans
repository:
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_squash_merge: true
  default_branch: master
  has_issues: true
  has_wiki: true
  private: false
labels:
  - name: bug
    color: CC0000
